### PR TITLE
Reformat whitespace according to PEP8

### PR DESCRIPTION
**Pull request by tocic**
Automatically reformat using the following command: 

```shell
autopep8 --ignore=E302,E401,E402,E501 --in-place --recursive "quiz/" "cppquiz/"
```

And then manually exclude the code that is commented out, since `autopep8` doesn't support the `pycodestyle`'s error E114.

### CODE REVIEW

**Comment by knatten** [comment]
I found a nice way to run it on the full repo by using `.gitignore` to create the exclude list. I also want to improve the CI setup a bit and integrate this in the GitHub actions workflow. I'll make another PR which fixes all of that.

**Comment by knatten** [comment]
What do you think about https://github.com/knatten/cppquiz/pull/272? It runs on the full root directory, and I only had to ignore E402. It also adds a script to do formatting for you, enforces the formatting in CI, and requires no manual fixups.

**Comment by tocic** [comment]
I didn't want to completely reformat the codebase to not impose a code style on you. As the original author, you may have some preffered style and it's the golden standard for this repo :) As for me, I fully endorse the complete PEP8 complience and running the formatter in CI.

- by 

> manually exclude the code that is commented out

I meant lines like these:

https://github.com/knatten/cppquiz/blob/2e6922811aa3ebf7997ffadcbc90f5fb4ad17e33/cppquiz/settings.py#L79-L81

In your PR it's reformatted like 

```diff
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
-#    'django.contrib.staticfiles.finders.DefaultStorageFinder',
+   #    'django.contrib.staticfiles.finders.DefaultStorageFinder',
```

If you'll decide to uncomment that in future you'll get

```python
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
        'django.contrib.staticfiles.finders.DefaultStorageFinder',
```

instead of preffered

```python
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'django.contrib.staticfiles.finders.DefaultStorageFinder',
```

It can't be ignored using an `autopep8`'s rule, so I fixed these cases manually.

- E302,E401,E402,E501 — these are for 
    - leave 1 line between functions, since I thought it's the preferred style
    - leave single-line imports, ditto
    - don't move `from . import local_settings`
    - don't reformat long lines, ditto
- 

> Is it possible to run it on the full repo? Then it will automatically pick up any new directories we add to the top level later.

Definitely, I just didn't want to recursively search in unrelated dirs on my local machine.

**Comment by knatten** [comment]
> I didn't want to completely reformat the codebase to not impose a code style on you. As the original author, you may have some preffered style and it's the gold standard for this repo :). As for me, I fully endorse the complete PEP8 compliance and running the formatter in CI.

Haha, thanks! No there's no thought at all behind the formatting here. Most of this code was written drunk at night at an ACCU conference and on the train/plane back home. There are no gold standards in this code base! :D

> * by
> 
> > manually exclude the code that is commented out
> 
> I meant lines like these:
> 
> https://github.com/knatten/cppquiz/blob/2e6922811aa3ebf7997ffadcbc90f5fb4ad17e33/cppquiz/settings.py#L79-L81
> 
> In your PR it's reformatted like
> 
> ```diff
>     'django.contrib.staticfiles.finders.AppDirectoriesFinder',
> -#    'django.contrib.staticfiles.finders.DefaultStorageFinder',
> +   #    'django.contrib.staticfiles.finders.DefaultStorageFinder',
> ```
> 
> If you'll decide to uncomment that in future you'll get
> 
> ```python
>     'django.contrib.staticfiles.finders.AppDirectoriesFinder',
>         'django.contrib.staticfiles.finders.DefaultStorageFinder',
> ```
> 
> instead of preffered
> 
> ```python
>     'django.contrib.staticfiles.finders.AppDirectoriesFinder',
>     'django.contrib.staticfiles.finders.DefaultStorageFinder',
> ```
> 
> It can't be ignored using an `autopep8`'s rule, so I fixed these cases manually.

I see, I fixed some of those too in my PR. I'll have a look for more, but I don't really care too much. As long as we have a stable formatter so we avoid back and forth, that's the most important to me.
 
> * E302,E401,E402,E501 — these are for
>   
>   * leave 1 line between functions, since I thought it's the preferred style
>   * leave single-line imports, ditto
>   * don't move `from . import local_settings`
>   * don't reformat long lines, ditto

Right, I think I ended up with something I like in my PR now

> > Is it possible to run it on the full repo? Then it will automatically pick up any new directories we add to the top level later.
> 
> Definitely, I just didn't want to recursively search in unrelated dirs on my local machine.

Right. I fixed it by using `.gitignore` in my PR.

Thanks a lot for the help!

**Pull request closed without merging**
