### PR TITLE
Fixed regex for links to standard

### PR DESCRIPTION
**Pull request by vsklamm**
Fix for #156

### CODE REVIEW

**Comment by knatten** [comment]
Thanks a lot for fixing! I'll look into this in a few days.

**Comment by knatten** [comment]
I agree with your change from `\S` to `\w` in `possible_named_reference`. But I don't understand the added `after_char`, what is it for?

It seems to me that the `'\(?'` and `'\)?'` are not needed when concatenating the final regex. I don't remember why I added those in the first place. Maybe the patch below is a cleaner fix, what do you think? .

```diff
diff --git a/cppquiz/quiz/templatetags/quiz_extras.py b/cppquiz/quiz/templatetags/quiz_extras.py
index 7cd10a2..1bc55b4 100644
--- a/cppquiz/quiz/templatetags/quiz_extras.py
+++ b/cppquiz/quiz/templatetags/quiz_extras.py
@@ -18,10 +18,10 @@ def format_paragraph(section_name, paragraph_number, full_text):
         return "<em>" + full_text + "</em>"

 def standard_ref(text):
-    possible_named_reference = u'(\[(\S+(\.\S+)*)\])?'
+    possible_named_reference = u'(\[(\w+(\.\w+)*)\])?'
     numbered_reference = u'§\d+(\.\d+)*'
     possible_pilcrow_reference = u'(¶(\d+(\.\d+)*))*'
-    regex = re.compile('(' + possible_named_reference + '\(?' + numbered_reference + '\)?' + possible_pilcrow_reference + ')')
+    regex = re.compile('(' + possible_named_reference + numbered_reference + possible_pilcrow_reference + ')')
     matched = regex.findall(text)
     for elem in matched:
         full_paragraph = elem[0]
```

It's really cool that you took the time to go through and find some error cases! Do you think you could add some more of those to the unit tests?

**Comment by vsklamm** [comment]
Yes, `\(?` and `\)?` is unnecessary, I think.

`after_char` is needed for this case: https://regex101.com/r/2v65Xb/4
There is the substring `[lex.string]§5.13.5¶1` of `[lex.string]§5.13.5¶16` in explanation so in for-loop
https://github.com/knatten/cppquiz/blob/76723f25459d122d1e5e6708a129a021c2c0f6e1/cppquiz/quiz/templatetags/quiz_extras.py#L25-L32
it replaces the `[lex.string]§5.13.5¶1` twice (also as a substring). My simple solution is based on the fact that the symbol after the pattern should not be a digit (like in  `[lex.string]§5.13.5¶1`**6**)

**Comment by knatten** [comment]
Right, I think that can be solved in a simpler way by asking `text.replace` to only replace the first occurrence. Since we're iterating over the regex matches in order, if we then only replace them one at a time in the same order, that should work, right?

```diff
$ git diff master -- cppquiz/quiz/templatetags/quiz_extras.py
diff --git a/cppquiz/quiz/templatetags/quiz_extras.py b/cppquiz/quiz/templatetags/quiz_extras.py
index 7cd10a2..23d66b9 100644
--- a/cppquiz/quiz/templatetags/quiz_extras.py
+++ b/cppquiz/quiz/templatetags/quiz_extras.py
@@ -18,17 +18,17 @@ def format_paragraph(section_name, paragraph_number, full_text):
         return "<em>" + full_text + "</em>"
 
 def standard_ref(text):
-    possible_named_reference = u'(\[(\S+(\.\S+)*)\])?'
+    possible_named_reference = u'(\[(\w+(\.\w+)*)\])?'
     numbered_reference = u'§\d+(\.\d+)*'
     possible_pilcrow_reference = u'(¶(\d+(\.\d+)*))*'
-    regex = re.compile('(' + possible_named_reference + '\(?' + numbered_reference + '\)?' + possible_pilcrow_reference + ')')
+    regex = re.compile('(' + possible_named_reference + numbered_reference + possible_pilcrow_reference + ')')
     matched = regex.findall(text)
     for elem in matched:
         full_paragraph = elem[0]
         section_name = elem[2]
         paragraph_number = elem[6]
         text = text.replace(full_paragraph,
-           format_paragraph(section_name, paragraph_number, full_paragraph))
+           format_paragraph(section_name, paragraph_number, full_paragraph), 1)
```

**Comment by vsklamm** [comment]
Our both solutions fail at added test:)

**Comment by knatten** [comment]
🤦‍♂ Thanks for spotting that. My solution fails because when it's time to replace the second reference, `text.replace` will instead pick up the reference inside the link that was already transformed.
 
I don't have time to investigate this weekend, but I think the proper solution would be using `re.sub()` with a callback which transforms the match to an url. Since then we're doing detection and replacements in the same "loop", and it actually knows what part to replace.

**Comment by vsklamm** [comment]
With `sub()` it works fine

**Comment by knatten** [comment]
Sorry for not getting back to you quicker. The idea of using `sub` was to avoid the for loop entirely, and avoid the "replacing the wrong thing" problem in the first place.

I suggest we do it like this:

```python
# -*- coding: utf-8 -*-
import re
import markdown

from django import template
from django.utils.safestring import mark_safe

register = template.Library()

def format_reference(match):
    full_reference = match.group(0)
    section_name = match.group('section_name')
    paragraph_number = match.group('paragraph')
    if section_name:
        full_link = "https://timsong-cpp.github.io/cppwp/n4659/" + section_name
        if paragraph_number:
            full_link = full_link + "#" + paragraph_number
        return "<em><a href=\"" + full_link + "\">" + full_reference + "</a></em>"
    else:
        return "<em>" + full_reference + "</em>"

def standard_ref(text):
    possible_section_name = u'(\[(?P<section_name>\w+(\.\w+)*)\])?'
    section_number = u'§\d+(\.\d+)*'
    possible_paragraph = u'(¶(?P<paragraph>\d+(\.\d+)*))*'
    regex = re.compile('(' + possible_section_name + section_number + possible_paragraph + ')')
    return re.sub(regex, format_reference, text)

def custom_linebreaks(text):
    return (text
        .replace("\n", "<br />")
        .replace("</p><br />", "</p>")
        .replace("<br /><p>", "<p>")
        .replace("</pre><br />", "</pre>"))

@register.filter(needs_autoescape=True)
def to_html(text, autoescape=None):
    return mark_safe(
        standard_ref(
            custom_linebreaks(
                markdown.markdown(text))))
```

What do you think?

**Comment by knatten** [comment]
Since this stagnated, I made #162 which is intended to replace it. See more details there.

**Comment by knatten** [comment]
Replaced by #162

**Pull request closed without merging**
